name: Release
on:
  push:
    tags: 
      - v*
jobs:
  release:
    name: Building and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image and push to DockerHub
        run: sh ./build.sh